### PR TITLE
Improve grammar.

### PR DESCRIPTION
**Pull request by mdosch**
I am no native english speaker, but for me this sounds
a lot better. Comment of a native speaker is very
much appreciated.

### CODE REVIEW

**Comment by jubalh** [comment]
I had the same urge some time ago :D :D 
Then contacted some UK native and they told me that both is equally fine.

However I think we can still take this to make us non native English speakers feel better :D :D

**Comment by mdosch** [comment]
Just now MattJ told me both are fine and the first one sounds more natural. I am pretty surprised, but in this case I think we better don't touch it.

**Comment by jubalh** [comment]
I was surprised as well :D

**Comment by jubalh** [comment]
Closing as discussed with @mdosch

**Pull request closed without merging**
