### PR TITLE
Add custom `assert()` (`PROF_ASSERT()`)

### LINKED ISSUE #1895: Change assert behavior
Currently, we have many "asserts" in a code that would cause a crash and not every time it is possible to reproduce, as well as dump might be unavailable. I propose to use wrapper over a default "assert" (or even a custom solution) which would add logging, which can provide us additional data on the issues.

@sjaeckel @pasis , I would gladly hear your opinion on this considering your level of expertise in deep topics as such.

### PR DESCRIPTION
**Pull request by H3rnand3zzz**
See commit message.

Valgrind not needed in this case.

### How to test the functionality
* Cause assert failure or add custom assert that will certainly fail.

Resolve #1895

### CODE REVIEW

**Comment by H3rnand3zzz** [comment]
@jubalh @sjaeckel @pasis, if someone kindly can find a time to review it, it would be amazing.

**Comment by jubalh** [comment]
Personally I fail to see the reason for it.
For this reason, plus pasis being the author of pppoat2, I thought it's best if pasis and sjaeckel review it.

**Comment by H3rnand3zzz** [comment]
> Personally I fail to see the reason for it. For this reason, plus pasis being the author of pppoat2, I thought it's best if pasis and sjaeckel review it.

The reason is on plain site: to make debugging easier. If someone has assert problem, he can provide profanity.log containing a line that shows where the problem has happened. Otherwise we need coredump, which not all the users can provide.

**Comment by jubalh** [comment]
That's exactly what I mean. For me it is default that under Linux we check things using gdb, get backtrace, receive a coredump from users.
For me this and https://profanity-im.github.io/issues.html seems to be enough and seems to be the standard way in the Linux world.
So for me it is not visible why we need this and what downsides it could bring. Which is why I will let someone else review it :)

**Comment by jubalh** [comment]
Not a big fan of this. And since noone else reviewed yet I'll close.

**Pull request closed without merging**
