### PR TITLE
Don't add the same command twice to history

### PR DESCRIPTION
**Pull request by H3rnand3zzz**
See commit messages.

### CODE REVIEW

**Comment by jubalh** [comment]
>  Fix history duplicates

History is actually a broad term in our client :)
Maybe be a little more specific like: `Don't add the same command twice to history` or something.

> Bug is fixed by introducing check.

I don't consider this a bug. For example in bash you can also configure this behaviour. If you want to each line you type added or remove duplicates.

BTW did you check whether readline maybe even has an option for this? Maybe via inputrc?

**Review by jubalh — APPROVED** [review]
Commit message still refercnes "bug" otherwise good to go :)

**Review by sjaeckel — APPROVED** [review]
> BTW did you check whether readline maybe even has an option for this? Maybe via inputrc?

Did you check?

**Comment by H3rnand3zzz** [comment]
> > BTW did you check whether readline maybe even has an option for this? Maybe via inputrc?
> 
> Did you check?

https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File-Syntax.html
Haven't found any mention of setting like this one

**Comment by jubalh** [comment]
Thank you!

**Pull request merged**
