### PR TITLE
Use Gmainloop as a main loop to increase performance

### PR DESCRIPTION
**Pull request by H3rnand3zzz**
Potential improvements:
 - [x] Further testing to make sure that no additional issues are introduced.
---
- [ ] I ran valgrind when using my new feature

Current version significantly improves performance, especially noticeable on alt+scroll.

### CODE REVIEW

**Comment by jubalh** [comment]
Thanks for working on this!

Started in https://github.com/profanity-im/profanity/pull/1629.
@rodarima could you also review?

**Comment by rodarima** [comment]
I gave it a quick look and looks good, but I haven't tested it. Thanks for resurrecting this :-)

**Comment by jubalh** [comment]
I'm running this on my local machine since today, so far it seems to work fine.

@H3rnand3zzz did you measure any performance improvements?

I wonder how much it gives us so far, and without https://github.com/strophe/libstrophe/pull/191.

We also should link to https://github.com/profanity-im/profanity/issues/1246

**Comment by H3rnand3zzz** [comment]
@sjaeckel @jubalh any updates?

**Comment by jubalh** [comment]
I ran this since a couple of days and didn't find any issues.
But I also have only a limited usecase. Let's merge it and see what others find. In the worst case we will revert back.

**Pull request merged**
