### PR TITLE
AESGCM upload tool

### PR DESCRIPTION
**Pull request by wstrm**
Refactor the _add_omemo_stream voodoo into an upload tool.

- [ ] Make it buildable without OMEMO support enabled
- [ ] Debug 400 errors

### CODE REVIEW

**Comment by jubalh** [comment]
@wstrm any news on this one?

**Comment by jubalh** [comment]
@wstrm any chance we can resurrect you to finish this PR? Would be great to have this in 0.12.

**Comment by jubalh** [comment]
@wstrm last call for 0.12 :-)

**Comment by binex-dsk** [comment]
> Make it buildable without OMEMO support enabled

Use the `HAVE_OMEMO` macro for this.

**Comment by jubalh** [comment]
@wstrm do you plan to finish this?

**Comment by jubalh** [comment]
Unfortunately neither got a response here nor via PM.
Going to close this.

**Pull request closed without merging**
