### PR TITLE
Fix `prof_pre_chat_message_display` does not replace sent messages + minor refactoring

### LINKED ISSUE #1917: `prof_pre_chat_message_display` does not replace sent messages
## Expected Behavior
`prof_pre_chat_message_display` is being called for sent messages as well

## Current Behavior
It's being called only for loaded messages from the DB (sent and received), but not for sent messages. First report is here https://github.com/profanity-im/profanity-plugins/issues/23

## Possible Solution
call it for sent messages as well

## Steps to Reproduce (for bugs)

1. `/plugins install https://raw.githubusercontent.com/profanity-im/profanity-plugins/master/stable/emoticons.py`
2. Send a message
3. Message is not being replaced
4. `/close` and `/msg same_recipient` and you'll see that replacement works.

## Environment
Master branch

### PR DESCRIPTION
**Pull request by H3rnand3zzz**
### How to test the functionality
 - /plugins install https://raw.githubusercontent.com/profanity-im/profanity-plugins/master/stable/emoticons.py
 - Send a message with emoticons. E.g. `Hello, how are you today? :)`
 - Message is being **replaced**

Fix #1917

### CODE REVIEW

**Comment by H3rnand3zzz** [comment]
### Revision-1
Rebased on master

**Comment by H3rnand3zzz** [comment]
What a mess... Further revisions are intended just to clean it up.

**Comment by H3rnand3zzz** [comment]
### Revision-2
Change memory handling to suggested by @sjaeckel method.

**Comment by H3rnand3zzz** [comment]
### Revision 4

 - Further improvements based on @sjaeckel suggestions.
 - Significantly improved commit messages.

**Review by jubalh — APPROVED** [review]
Looks good to me. Since jaeckel was involved I will also set him as reviewer and wait for it.

**Review by sjaeckel — APPROVED** [review]

**Pull request merged**
