### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by sjaeckel**
- [x] I ran valgrind when using my new feature

Check commit messages for details.

### CODE REVIEW

**Review by jubalh — APPROVED** [review]
Interesting stuff!
Code looks good. I would prefer to have a little more text in the commit messages of "fix reconnect" and "window NULL issue" though.
In the first one a little explanation or thought process and in the second maybe a little description  what's happening there.
Sure I know which bug this is but might be that in some years I will forget or someone else tries to figure out what's done..

**Comment by H3rnand3zzz** [comment]
LGTM. Checked `/reconnect now` and auto reconnect after forceful server disconnect. Both cases worked great, without any problems.

**Comment by jubalh** [comment]
> It might be a good idea to add reference to https://github.com/profanity-im/profanity/issues/1846 in the /fix `/reconnect now` commit message.

Agreed.

**Comment by sjaeckel** [comment]
> I would prefer to have a little more text in the commit messages

better?

**Comment by jubalh** [comment]
> better?

perfect!

**Pull request merged**
