### PR TITLE
Reset things on connection loss

### PR DESCRIPTION
**Pull request by jubalh**
Remove the windows, clear tls certs, clean omemo.
Regards https://github.com/profanity-im/profanity/issues/1089

### CODE REVIEW

**Comment by jubalh** [comment]
@paulfariello can you review regarding the omemo part?

**Comment by kaffeekanne** [comment]
i am testing this PR as i had frequent connection losses before. but since my server migrated from prosody to ejabberd, i am unsure if i confirm the fix.

**Comment by paulfariello** [comment]
@jubalh it's ok for me :)

**Comment by jubalh** [comment]
Thank you both.
I'll merge this now.
Let's do further testing on master.

**Pull request merged**
