### PR TITLE
package

### PR DESCRIPTION
**Pull request by ragu-1997**
Net-tools is the networking tools.
That is most important why because verify what are the ports are running inside the container (use this command netstat -ntlp)
so, we easily avoid some networking vulnerability.
**Use case:
monitor the networking process and ports**

### CODE REVIEW

**Comment by jubalh** [comment]
I saw now that you edited here on GitHub.

But the final commit later also needs to contain the information and also needs to follow the guidelines mentioned in CONTRIBUTING.md.

The Dockerfile you are editing is for running our CI. So I'm slightly puzzled what your change should do.

**Comment by jubalh** [comment]
Still waiting for your explanation/answer.

**Comment by ragu-1997** [comment]
Sorry for the late reply Micheael

Unfortunately i misunderstood the code and scenario you are wright thanks
for your time and effort

**Comment by jubalh** [comment]
No problem. Keep up investigating, maybe you find something to improve!

**Comment by ragu-1997** [comment]
Sure

**Pull request closed without merging**
