### PR TITLE
Document custom input configuration in man page

### PR DESCRIPTION
**Pull request by paulfertser**

### CODE REVIEW

**Comment by jubalh** [comment]
Looks good!
I assume you saw https://profanity-im.github.io/guide/latest/keybindings.html as well?

**Comment by paulfertser** [comment]
On Wed, Mar 30, 2022 at 12:53:03PM -0700, Michael Vetter wrote:
> Looks good!
> I assume you saw [1]https://profanity-im.github.io/guide/latest/keybindings.html
> as well?

Heh, in fact, no, as it's not part of the repository. I did "git grep
-i" in profanity sources to make sure I wasn't missing anything, I'm
used to having all documentation maintained along with the source code
in a single repo just because of it.

**Comment by jubalh** [comment]
Just clone the website repo as well and grep there too :)

**Comment by paulfertser** [comment]
On Wed, Mar 30, 2022 at 02:10:54PM -0700, Michael Vetter wrote:
> Just clone the website repo as well and grep there too :)

Guess I'd need to use "git subtree" trickery for "git grep" to work
with that. Sounds kinda like a plan but I still do not like the idea
that only part of the documentation is available online, and
everything else needs to be fetched from the Internet somehow.

**Comment by jubalh** [comment]
Anyways I'm only linking you this website in case you want to use more information from there in the manpage. Or vice versa.

**Comment by jubalh** [comment]
I remember when I started using Profanity I always was looking for all this information locally! I guess I just got used to it. But now it's cool when we improve this :)

**Comment by jubalh** [comment]
So you want to leave this PR like this? Then I'm going to merge.

**Review by jubalh — APPROVED** [review]

**Pull request merged**
