### PR TITLE
Fix not autocompleting nicks with '/'

### PR DESCRIPTION
**Pull request by MarcoPolo-PasTonMolo**
Remove check for '/' at the beginning of the line before autocompleting
and make it fallback to command autocompletion if no nicks found.

Fixes https://github.com/profanity-im/profanity/issues/1474

### CODE REVIEW

**Comment by jubalh** [comment]
When testing this PR I discovered: https://github.com/profanity-im/profanity/issues/1647

Regarding this PR:
Looks good! And solves the mentioned issue indeed!

However there is one down side to the current implementation. Let's say a user joins with the nickname `/sendfile` then autocompletion will always autocomplete to this nick (`'/sendfile:`) and not do any file completion for `/sendfile ~/myfile` anymore.

So it's a question what behaviour do we want?

My opinion is that another user shouldn't be able to limit the functionality of the client. So the proper  autocompletion profanity commands is more important.

What to do? Not complete nicknames starting with `/` at all?

**Comment by MarcoPolo-PasTonMolo** [comment]
> My opinion is that another user shouldn't be able to limit the functionality of the client. So the proper autocompletion profanity commands is more important.

I agree.

> What to do? Not complete nicknames starting with / at all?

Maybe?

**Comment by jubalh** [comment]
> Maybe?

Yes, let's do it this way :)

**Comment by MarcoPolo-PasTonMolo** [comment]
Do I have to do something? As I understand it just closing this pull request and related issue without merging it would be what we want

**Comment by jubalh** [comment]
Oh? I thought we just turn it around. Like first checking for commands and autocompleting them and otherwise autocompleting the nick.

Which means we will autocomplete all nicks (even the ones starting with `/`) and only leave out the ones that start with `/` and are a profanity command as well.

Am I missing something?

**Comment by MarcoPolo-PasTonMolo** [comment]
I see, I just misunderstood you. Ok I'll fix it

**Review by jubalh — APPROVED** [review]

**Pull request merged**
