### PR TITLE
Fix chatlogs for outgoing carbons

### PR DESCRIPTION
**Pull request by jubalh**
Doesn't make sense to log if plain is not set in all cases.

Regards https://github.com/profanity-im/profanity/issues/1439

### CODE REVIEW

**Comment by jubalh** [comment]
@aereaux could you test whether this solves https://github.com/profanity-im/profanity/issues/1439 ?

**Comment by aereaux** [comment]
It looks like this does not fix it, unfortunately.

**Comment by jubalh** [comment]
What about additionally:

```
diff --git a/src/event/server_events.c b/src/event/server_events.c
index 27f142eb..f2d8aea4 100644
--- a/src/event/server_events.c
+++ b/src/event/server_events.c
@@ -659,14 +659,19 @@ sv_ev_incoming_carbon(ProfMessage* message)
 #endif
     }
 
+    gboolean logit = TRUE;
+    if (message->type == PROF_MSG_TYPE_MUCPM) {
+        logit = FALSE;
+    }
+
     if (message->enc == PROF_MSG_ENC_OX) {
-        _sv_ev_incoming_ox(chatwin, new_win, message, FALSE);
+        _sv_ev_incoming_ox(chatwin, new_win, message, logit);
     } else if (message->encrypted) {
-        _sv_ev_incoming_pgp(chatwin, new_win, message, FALSE);
+        _sv_ev_incoming_pgp(chatwin, new_win, message, logit);
     } else if (message->enc == PROF_MSG_ENC_OMEMO) {
-        _sv_ev_incoming_omemo(chatwin, new_win, message, FALSE);
+        _sv_ev_incoming_omemo(chatwin, new_win, message, logit);
     } else {
-        _sv_ev_incoming_plain(chatwin, new_win, message, FALSE);
+        _sv_ev_incoming_plain(chatwin, new_win, message, logit);
     }
     rosterwin_roster();
     return;
```

**Comment by jubalh** [comment]
@aereaux I pushed it to this branch too. Maybe you can test this branch again.

**Comment by aereaux** [comment]
Looks to me like this fixes it now.  Thanks!

**Comment by jubalh** [comment]
Great! Thanks for testing!

**Pull request merged**
