### PR TITLE
MUC: Show offline members in sidebar

### PR DESCRIPTION
**Pull request by xenrox**
For small, private rooms I like to always see a list of members, even if they are offline. This works in e.g. conversejs.

I mainly got the idea from https://github.com/profanity-im/profanity/pull/1242

This PR is not fully working as intended: When first starting profanity it only shows a small subset of members. As soon as you let profanity redraw its window (change to fullscreen), the list becomes mostly correct (besides some double entries).

What is still missing: Option to toggle setting, code duplication, filter out online users from list

Alternative idea: Try to read what `/affiliation list` sees

### CODE REVIEW

**Comment by jubalh** [comment]
> This PR is not fully working as intended: When first starting profanity it only shows a small subset of members. As soon as you let profanity redraw its window (change to fullscreen), the list becomes mostly correct (besides some double entries).

There is a function to force a redraw.

**Comment by xenrox** [comment]
I am redrawing now at a point where the program should have the correct list returned by `muc_members`. Otherwise OMEMO encryption would not work in rooms.

**Comment by xenrox** [comment]
Since dismail seems to be down right now, here is a status update:

Code deduplication is done and the offline list should be filtered correctly now.
The only thing that could be missing is a setting to toggle displaying the list.
If you want that, please tell me what command should be used.

**Comment by jubalh** [comment]
> If you want that, please tell me what command should be used.

Maybe according to `/roster show|hide offline` we could have an `/occupants show|hide offline`.

**Comment by xenrox** [comment]
I think that everything should be done now.

**Review by jubalh — APPROVED** [review]
Looks very good! Thanks for this patch!
The setting isn't saved per channel nor generally right now but for me that's okay.

**Comment by jubalh** [comment]
Thanks! I hope you contribute more to Profanity! Do you plan to? ;)

**Comment by xenrox** [comment]
> The setting isn't saved per channel nor generally right now but for me that's okay.

Generally should work right now with `/occupants default show offline` followed by `/save` or do you mean something different?

> Thanks! I hope you contribute more to Profanity! Do you plan to? ;)

Probably, since XMPP is my primary messenger now, especially if I find a bug or another interesting feature to work on.

**Comment by jubalh** [comment]
> Generally should work right now with /occupants default show offline followed by /save or do you mean something different?

Oh seems I missed that haha.

> Probably, since XMPP is my primary messenger now, especially if I find a bug or another interesting feature to work on.

Glad to hear!

**Pull request merged**
