### PR TITLE
Clean-up task: clean up feature defines

### PR DESCRIPTION
**Pull request by DebXWoody**

### CODE REVIEW

**Comment by DebXWoody** [comment]
I changed implementation of the files

- src/command/cmd_funcs.c
- src/event/client_events.c
- src/event/server_events.c

Problem:

The implementation of some functions has been split by _feature defines_ like:

```
// OTR suported, PGP supported, OMEMO unsupported
#ifdef HAVE_LIBOTR
#ifdef HAVE_LIBGPGME
#ifndef HAVE_OMEMO
do()
#endif
#endif
#endif

// OTR supported, PGP unsupported, OMEMO unsupported
#ifdef HAVE_LIBOTR
#ifndef HAVE_LIBGPGME
#ifndef HAVE_OMEMO
do()
#endif
#endif
#endif
```

It's quite difficult to tests and to understand the code. I change the implementation and removed the code and replaced it by the code which has been used for all feature defines.

Code which depends on functions which are not included, I changed the implementation by using a flag like this:

```
gboolean handled = FALSE;
#ifdef HAVE_LIBOTR
         handled = otr_on_message_send(chatwin, plugin_msg, request_receipt, replace_id);
#endif
```

I started to tests the changes. Plain text and OMEMO looks good. With pgp I saw one issue. The client shows `[online] [PGP send/recv]` but it's send via OMEMO. :shrug:

**Comment by jubalh** [comment]
OTR seems to work fine (tested while all deps are present)

**Comment by mdosch** [comment]
I ran this code for a few days and had no problems. I used OMEMO and PGP encryption.

**Comment by jubalh** [comment]
Nice! Going to merge this soon. But wonder why for @DebXWoody PGP didn't work?

**Comment by jubalh** [comment]
Seems it works fine! Lets expose it to more testers ;)

**Pull request merged**
