### PR TITLE
Feature/704 ui behaviour reconnect

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by kaffeekanne** [comment]
have not tested this PR, but keep in mind we could lose messages that are sent between disconnection and reconnection. fetching the history and comparing with alreaddy written chatlogs is probably a lot and error prone work, but what do you think about it? would be poormans MAM ;)

**Comment by jubalh** [comment]
Yep you are right about this :)

I save the timestamp of the last message we received in MUC (general for all MUCs not for each one), and when we rejoin and we get the MUC history I check if the messages have newer timestamps. In which case they get displayed.
In my tests it worked :)

**Comment by paulfariello** [comment]
Could we use message id to filter which history messages we have to display ?

**Comment by jubalh** [comment]
> Could we use message id to filter which history messages we have to display ?

Then we would have to save all IDs since they are not numerated. Sounds a bit much right?
But based on your input I saw that I could implement this at another postion (src/xmpp/message.c) where we already test for the timestamp. Thanks!

**Comment by paulfariello** [comment]
You are right and we can't use id if they are not in received MUC history. But they will be required when we'll have MAM and OMEMO support.

**Comment by jubalh** [comment]
I think I'll merge this tomorrow.

**Pull request merged**
