### PR TITLE
add raw command

### PR DESCRIPTION
**Pull request by akaWolf**
see https://github.com/profanity-im/profanity/pull/1662#issuecomment-1082841202

### CODE REVIEW

**Comment by jubalh** [comment]
Please expand the description a little. To explain to a user what sending raw means.

**Comment by akaWolf** [comment]
> Please expand the description a little. To explain to a user what sending raw means.

done

**Comment by paulfertser** [comment]
Looks like this adds the third almost identical function for /editor (the other two being _inp_rl_send_to_editor() and cmd_editor()) :/

**Comment by jubalh** [comment]
Then I guess we don't need this.

**Pull request closed without merging**
