### PR TITLE
Use travis matrix to test more systems (#1100)

### PR DESCRIPTION
**Pull request by optmzr**
## Add Travis CI tests for Arch, Debian and OSX/macOS

+ Arch and Debian are run in Docker containers, as openSUSE Tumbleweed.

+ OSX/macOS doesn't use any containers.
   * Homebrew is used to fetch all the dependencies.
   * The dependencies are declared in the Brewfile.travis file.

+ The travis-build.sh script has been modified to check for the current
  OS and the different configure flags has been moved into an array
  that'll be looped through instead.
  The xscreensaver (for libXScrnSaver) flags has been removed for macOS
  as it only makes sense for systems running X11, which macOS doesn't
  (usually) do.

+ Some minor shellcheck fixes, too.

Fixes: #1100

### CODE REVIEW

**Comment by jubalh** [comment]
:-)

**Comment by jubalh** [comment]
I hand you the travis osx hero badge now!

**Comment by optmzr** [comment]
@jubalh Only took 36 commits :sunglasses:

**Comment by optmzr** [comment]
Yes! I'll fix :)

**Comment by optmzr** [comment]
@jubalh Fixed.

I also noted that Travis CI has support for Windows too:
https://blog.travis-ci.com/2018-10-11-windows-early-release
https://travis-ci.community/c/environments/windows

Here's one project doing it:
https://travis-ci.org/yargs/yargs/jobs/439923030

Maybe something for the future? :)

**Comment by jubalh** [comment]
Cool! Yeah maybe :-)

I don't have any Windows machine but I planned to bug a friend to test the current Window documentation.
I'm not sure how Windows+Cygwin play together but it seems that this was the preferred way to install profanity.


> https://blog.travis-ci.com/2018-10-11-windows-early-release

So they use chocolatey, which seems to be nice. It doesn't have libxml packaged yet (which we need for libstrophe/libmesode). Probably more stuff missing.

I thought maybe telling windows users to install the Linux subsystem for Windows (and install openSUSE) so they only need to do a `zypper in profanity` might be an alternative for people who don't want to build themselves.

**Comment by jubalh** [comment]
@optmzr thanks a lot for the work on this! :)

**Pull request merged**
