### PR TITLE
Cleanup: gchar as gchar instead of char

### PR DESCRIPTION
**Pull request by H3rnand3zzz**
See commit messages. Partially fixes/cleans up #1819 

- [x] Make cleanup
- [ ] Make it compatible with all build systems

### CODE REVIEW

**Comment by jubalh** [comment]
macos CI shows:
```
src/omemo/omemo.c:1335:9: error: cannot jump from this goto statement to its label
        goto out;
        ^
src/omemo/omemo.c:1346:23: note: jump bypasses initialization of variable with __attribute__((cleanup))
    auto_gchar gchar* device_id_str = g_strdup_printf("%d", device_id);
                      ^
src/omemo/omemo.c:1329:9: error: cannot jump from this goto statement to its label
        goto out;
        ^
src/omemo/omemo.c:1346:23: note: jump bypasses initialization of variable with __attribute__((cleanup))
    auto_gchar gchar* device_id_str = g_strdup_printf("%d", device_id);
                      ^
2 errors generated.
```

**Review by jubalh — APPROVED** [review]

**Comment by jubalh** [comment]
I think we can merge this already. Less conflicts later on. We can still find more cases later when we come by them.
Would you mind adding the issue number to the commit message as well?

**Comment by H3rnand3zzz** [comment]
Changes are incompatible with pikaur building routine
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=profanity-git

I am currently in search of the solution.

**Comment by jubalh** [comment]
> Changes are incompatible with pikaur building routine

We had a longer talk about this via 1:1 a while back.
It seems that all our CI builds fine with this. And to me the code looks good as well.

@H3rnand3zzz reported that when building with pikaur they get `may be used uninitialized` errors. But I think they are false positives. I don't know why they happen only on pikaur. We tried to compare compilers and flags passed to the compiler.

I would vote for merging this soon because it is a welcome change and so you don't get merge conflicts later on.

**Comment by H3rnand3zzz** [comment]
@jubalh I will try an alternative approach to this issue.

**Comment by jubalh** [comment]
Thanks @H3rnand3zzz !

to myself: never use GH UI to resolve conflicts.. ;)

**Pull request merged**
